### ISSUE TITLE
Alternative repo

### ISSUE THREAD

**Issue by faustinoaq** [benoist/intellij-crystal#3]
Hi @benoist Some people are working on Crystal plugin using Kotlin, take a look https://github.com/intellij-crystal/intellij-crystal

**Comment by keplersj** [comment]
`intellij-crystal` is a repo I had previously created and recently added to the `intellij` team in the new [crystal-lang-tools](https://github.com/crystal-lang-tools) organization. If you're still interested in this kind of integration we'd love to have you. The package there is written in Kotlin, largely based off `intellij-rust`, and has a very basic grammar at the moment, and above-all definitely needs some love.

**Comment by faustinoaq** [comment]
I'm cleaning my issue list :sweat_smile:

Reopen this if you want to
